"""empty message

Revision ID: 2409f11338cd
Revises: 4a0cab9950a
Create Date: 2015-05-18 22:02:26.611903

"""

# revision identifiers, used by Alembic.
revision = '2409f11338cd'
down_revision = '4a0cab9950a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'excerpt',
               existing_type=sa.VARCHAR(length=400),
               type_=sa.String(length=600),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'excerpt',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=400),
               existing_nullable=True)
    ### end Alembic commands ###
