"""empty message

Revision ID: 2b7bb0b50b29
Revises: 2370140125b7
Create Date: 2015-05-30 14:22:08.158277

"""

# revision identifiers, used by Alembic.
revision = '2b7bb0b50b29'
down_revision = '2370140125b7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('published_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'published_date')
    ### end Alembic commands ###
