"""empty message

Revision ID: 32e1cd1d94de
Revises: 47e6c9457213
Create Date: 2015-05-19 16:03:45.110397

"""

# revision identifiers, used by Alembic.
revision = '32e1cd1d94de'
down_revision = '47e6c9457213'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
