"""empty message

Revision ID: 3385636b798c
Revises: 341b490ef5a2
Create Date: 2015-05-30 20:42:01.388467

"""

# revision identifiers, used by Alembic.
revision = '3385636b798c'
down_revision = '341b490ef5a2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'excerpt')
    op.drop_column('post', 'body_html')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body_html', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('excerpt', sa.VARCHAR(length=600), autoincrement=False, nullable=True))
    ### end Alembic commands ###
