"""empty message

Revision ID: 341b490ef5a2
Revises: 2b7bb0b50b29
Create Date: 2015-05-30 15:03:05.706864

"""

# revision identifiers, used by Alembic.
revision = '341b490ef5a2'
down_revision = '2b7bb0b50b29'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'published_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('published_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
