"""empty message

Revision ID: 355b4e311a22
Revises: 287e4405a0a5
Create Date: 2015-08-13 02:12:27.892670

"""

# revision identifiers, used by Alembic.
revision = '355b4e311a22'
down_revision = '287e4405a0a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'project_owner_fkey', 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'user', ['owner_id'], ['id'])
    op.drop_column('project', 'owner')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key(u'project_owner_fkey', 'project', 'user', ['owner'], ['id'])
    op.drop_column('project', 'owner_id')
    ### end Alembic commands ###
