"""empty message

Revision ID: 3802844a16f1
Revises: 16f868a38787
Create Date: 2015-05-19 15:50:11.336538

"""

# revision identifiers, used by Alembic.
revision = '3802844a16f1'
down_revision = '16f868a38787'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
