"""empty message

Revision ID: 47e6c9457213
Revises: 581490b114fb
Create Date: 2015-05-19 15:59:46.571471

"""

# revision identifiers, used by Alembic.
revision = '47e6c9457213'
down_revision = '581490b114fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
