"""empty message

Revision ID: 5754bfe1a45f
Revises: 38d5248387e3
Create Date: 2015-07-19 21:41:38.713603

"""

# revision identifiers, used by Alembic.
revision = '5754bfe1a45f'
down_revision = '38d5248387e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'post_author_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'])
    op.drop_column('post', 'author')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(u'post_author_fkey', 'post', 'user', ['author'], ['id'])
    op.drop_column('post', 'author_id')
    ### end Alembic commands ###
