"""empty message

Revision ID: 581490b114fb
Revises: 3802844a16f1
Create Date: 2015-05-19 15:51:54.181073

"""

# revision identifiers, used by Alembic.
revision = '581490b114fb'
down_revision = '3802844a16f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
