"""empty message

Revision ID: 5a8f0c989415
Revises: 25035de76c5c
Create Date: 2015-08-15 18:58:42.940323

"""

# revision identifiers, used by Alembic.
revision = '5a8f0c989415'
down_revision = '25035de76c5c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('published', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'published')
    ### end Alembic commands ###
