"""empty message

Revision ID: 7654b42c2c
Revises: 22f11cd9af4
Create Date: 2015-05-12 13:07:41.497776

"""

# revision identifiers, used by Alembic.
revision = '7654b42c2c'
down_revision = '22f11cd9af4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pw_hash', sa.String(length=60), nullable=True))
    op.drop_column('user', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=60), nullable=True))
    op.drop_column('user', 'pw_hash')
    ### end Alembic commands ###
