"""empty message

Revision ID: bce8c978ba
Revises: 369a695c9c0
Create Date: 2015-05-16 16:52:11.685070

"""

# revision identifiers, used by Alembic.
revision = 'bce8c978ba'
down_revision = '369a695c9c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
