"""empty message

Revision ID: e84bc7009d
Revises: b398321a5
Create Date: 2015-05-12 11:07:10.141474

"""

# revision identifiers, used by Alembic.
revision = 'e84bc7009d'
down_revision = 'b398321a5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=60), nullable=True))
    op.drop_column('user', 'hometown')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hometown', sa.VARCHAR(length=60), nullable=True))
    op.drop_column('user', 'password')
    ### end Alembic commands ###
